### ISSUE TITLE
after run `gulp` events.js:85 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by 18601673727** [cheft/cheft#1]
```
Error: Cannot find module 'riot' from '/Users/xxx/react-demos/cheft/demo'
    at /Users/xxx/react-demos/cheft/demo/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/xxx/react-demos/cheft/demo/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/xxx/react-demos/cheft/demo/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/xxx/react-demos/cheft/demo/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/xxx/react-demos/cheft/demo/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/xxx/react-demos/cheft/demo/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```

**Comment by cheft** [comment]
这个东西还在实验阶段，目的是做一个riot同构框架，来取代传统的服务端渲染模式和SPA单页模式，目前还有很多问题。如果你想看的话，切到weixin分支吧，运行后先访问 /api/login/initdata 初始化数据，登录用户名密码是 admin/admin
