### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by joket1999** [cheft/cheft#10]
``` javascript
> cheft@0.0.2 start /Users/apple/Desktop/cheft-master
> node server

/Users/apple/Desktop/cheft-master/app/_components/breadcrumb/index.html:1
(function (exports, require, module, __filename, __dirname) { module.exports = riot.tag2('breadcrumb', '<section class="content-header"> <h1> {opts.name} <small></small> </h1> <ol class="breadcrumb"> <li><i class="fa fa-dashboard"></i> 主页</li> <li class="active">{opts.name}</li> </ol> </section>', '', '', function(opts) {
                                                                               ^

ReferenceError: riot is not defined
    at Object.<anonymous> (/Users/apple/Desktop/cheft-master/app/_components/breadcrumb/index.html:1:80)
    at Module._compile (module.js:397:26)
    at Object.require.extensions..html (/Users/apple/Desktop/cheft-master/lib/server.js:32:16)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/apple/Desktop/cheft-master/lib/server.js:45:21
    at Array.forEach (native)
    at recurse (/Users/apple/Desktop/cheft-master/lib/server.js:36:29)
    at /Users/apple/Desktop/cheft-master/lib/server.js:39:17
    at Array.forEach (native)
    at recurse (/Users/apple/Desktop/cheft-master/lib/server.js:36:29)
    at /Users/apple/Desktop/cheft-master/lib/server.js:39:17
    at Array.forEach (native)
    at recurse (/Users/apple/Desktop/cheft-master/lib/server.js:36:29)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! cheft@0.0.2 start: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cheft@0.0.2 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cheft package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get their info via:
npm ERR!     npm owner ls cheft
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Desktop/cheft-master/npm-debug.log
```

**Comment by webbrain-one** [comment]
Hi there, thanks for reporting this! I've opened a pull request to fix it: https://github.com/cheft/riot-isomorphic-template/pull/11. It ensures `riot` is loaded before the server tries to compile `.html` component templates, which should resolve the `ReferenceError: riot is not defined` error when running `node server` / `npm start`. Could you please test the PR and let me know if it works on your side?
